server:
  port: 8085
spring:
  application:
    name: gateway-api-service
  cloud:
    gateway:
      routes:
        - id: movie-catlog-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: movie-info-service
          uri: http://localhost:8081
          predicates:
            - Path=/movies/**
        - id: rating-data-service
          uri: http://localhost:8082
          predicates:
            - Path=/rating/**